[versions]
kotlin = "2.4.20"
compose = "1.12.0"
agp = "9.4.0"
material3 = "1.9.0"
gson = "2.13.2"
sdk-common = "32.4.0"
activity-compose = "1.10.1"

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
android-sdk-common = { module = "com.android.tools:sdk-common", version.ref = "sdk-common" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
